USE [master]
GO

/****** Object:  Database [StockDB]    Script Date: 10/07/2019 12:44:47 ******/
CREATE DATABASE [StockDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StockDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\StockDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StockDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\StockDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StockDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StockDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StockDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StockDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StockDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [StockDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StockDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StockDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StockDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StockDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StockDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StockDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StockDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StockDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StockDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StockDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StockDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StockDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StockDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StockDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StockDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StockDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StockDB] SET RECOVERY FULL 
GO

ALTER DATABASE [StockDB] SET  MULTI_USER 
GO

ALTER DATABASE [StockDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StockDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StockDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StockDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StockDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StockDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StockDB] SET  READ_WRITE 
GO


